version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "5001:5001"
    environment:
      - DB_HOST=mariadb
      - DB_USER=root
      - DB_PASSWORD=yourpassword
      - DB_NAME=yourdbname
    depends_on:
      # Use service_healthy to wait for the healthcheck to pass
      mariadb:
        condition: service_healthy
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    # New command to wait for the database before starting the Node.js app
    command: >
      /bin/sh -c "
      apk add --no-cache mariadb-client && \
      until mariadb-admin ping -h mariadb --silent; do
        echo 'Waiting for mariadb to be ready...'
        sleep 2
      done;
      npm start
      "

  mariadb:
    image: mariadb:11.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: yourdbname
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    # Healthcheck to determine when the database is ready
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s # Give the database some time to initialize before checking

volumes:
  mariadb_data: