# Use official Node.js LTS image
FROM node:20-alpine

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install only production dependencies
RUN npm install --production

# Copy the rest of your app files
COPY . .

# Expose port
EXPOSE 5001

# Start the app
CMD ["node", "index.js"]
